### ISSUE TITLE
Overlap w/ Survive Thirst

### ISSUE THREAD

**Issue by WenXin20** [ElenaiDev/ElenaiDodge2.0#5] opened 2021-02-12 02:10 UTC
`Minecraft v1.16.5`
`Forge v36.0.13`
`Elenai Dodge v2.0.1`
[`Survive v3.1.5`](https://www.curseforge.com/minecraft/mc-mods/survive)

The dodge bar is currently being overlapped by the thirst bar added by Survive.

![2021-02-11_17 52 46](https://user-images.githubusercontent.com/12000593/107722662-0e48fc80-6ca5-11eb-9540-a1d31b6e4254.png)

**Comment by ElenaiDev** [comment] 2021-02-12 12:26
This is unusual, however the issue may be at Survive's end as Elenai Dodge 2 appears correctly with similar mods such as Tough as Nails, Rustic and Armor Toughness Bar.

I've submitted an issue to their mod and will investigate it further, thank you for pointing this out!

**Comment by WenXin20** [comment] 2021-02-12 17:27
Thanks!

**Comment by ElenaiDev** [comment] 2021-04-03 17:34
Closing this (and should have sooner, so sorry for the notification!) as the issue is with Survive.

**Closed as completed by ElenaiDev** 2021-04-03 17:34 UTC

**Comment by WenXin20** [comment] 2021-04-03 17:43
Yeah, no problem.
