### ISSUE TITLE
[Optional] Adding enters to the weights config causes crashing

### ISSUE THREAD

**Issue by MitztheKat** [ElenaiDev/ElenaiDodge2.0#19] opened 2021-03-04 02:32 UTC
How did I discover this? - I was trying to sort out my .cfg file for future armor set additions.
Why do I want this fixed? - I almost *always* edit my configs via notepad++. It's habit. And AFAIK I can't go into the settings mid-game and paste stuff in? I might be wrong, I'll look into it and correct myself if not.
How difficult do I think this will be to fix? - Depending on how.. applicable the config from SOL-Potato is, either very easy or... difficult. I'm no MC modder but this may be out of range for a simple patch.
Why did I reference SOL Potato Edition? - their config has a similar (number, minecraft item/buff) thing. I think you could salv- i mean **borrow** the code from that mod :P

**Comment by ElenaiDev** [comment] 2021-03-04 14:18
Hi there!

So far I am unable to reproduce the issue, would you be able to send me your config file to look at?

Thanks so much!

**Comment by MitztheKat** [comment] 2021-03-04 15:48
[elenaidodge2-common.txt](https://github.com/ElenaiDev/ElenaiDodge2.0/files/6084791/elenaidodge2-common.txt)
This is before I load it in. (just change the .txt to .toml or whatever)
[elenaidodge2-common-broken.txt](https://github.com/ElenaiDev/ElenaiDodge2.0/files/6084861/elenaidodge2-common-broken.txt)
This is the config* after the game crashes from loading in.
I use notepad++ so... I don't know if you do.

**Comment by ElenaiDev** [comment] 2021-03-04 19:05
Hi there!

The issue is that you've added spaces and returns to the config file! Make sure you put all your weights on one line otherwise this will happen.

Basically, pressing enter (in terms of code) actually looks like \r\n  which means return and new line. This will cause a crash as it breaks the IDs!

Closing as the issue isn't on the mods end, hope this helps!

**Closed as completed by ElenaiDev** 2021-03-04 19:05 UTC
