### ISSUE TITLE
Cannot provide compatibility, could not find maven file

### ISSUE THREAD

**Issue by Jackiecrazy** [ElenaiDev/ElenaiDodge2.0#15] opened 2021-02-25 05:51 UTC
I followed the README ad verbatim, but cannot get the compat to work in my workspace. The repository is [here](https://github.com/Jackiecrazy/WarDance). 
```

    Could not resolve all files for configuration ':compileClasspath'.
> Could not find curse.maven:elenaidodge2-442962:3215435_mapped_snapshot_20201028-1.16.3.
  Searched in the following locations:
    - https://files.minecraftforge.net/maven/curse/maven/elenaidodge2-442962/3215435_mapped_snapshot_20201028-1.16.3/elenaidodge2-442962-3215435_mapped_snapshot_20201028-1.16.3.pom
    - https://files.minecraftforge.net/maven/curse/maven/elenaidodge2-442962/3215435_mapped_snapshot_20201028-1.16.3/elenaidodge2-442962-3215435_mapped_snapshot_20201028-1.16.3.jar
    - file:/home/jackiecrazy/.gradle/caches/forge_gradle/bundeled_repo/curse/maven/elenaidodge2-442962/3215435_mapped_snapshot_20201028-1.16.3/elenaidodge2-442962-3215435_mapped_snapshot_20201028-1.16.3.pom
    - file:/home/jackiecrazy/.gradle/caches/forge_gradle/bundeled_repo/curse/maven/elenaidodge2-442962/3215435_mapped_snapshot_20201028-1.16.3/elenaidodge2-442962-3215435_mapped_snapshot_20201028-1.16.3.jar
    - https://libraries.minecraft.net/curse/maven/elenaidodge2-442962/3215435_mapped_snapshot_20201028-1.16.3/elenaidodge2-442962-3215435_mapped_snapshot_20201028-1.16.3.jar
    - https://repo.maven.apache.org/maven2/curse/maven/elenaidodge2-442962/3215435_mapped_snapshot_20201028-1.16.3/elenaidodge2-442962-3215435_mapped_snapshot_20201028-1.16.3.pom
    - https://repo.maven.apache.org/maven2/curse/maven/elenaidodge2-442962/3215435_mapped_snapshot_20201028-1.16.3/elenaidodge2-442962-3215435_mapped_snapshot_20201028-1.16.3.jar
  Required by:
      project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

**Comment by ElenaiDev** [comment] 2021-02-25 08:37
Hi there!

Curse Maven takes a little while to update, and the file was only recently uploaded. You can check when it will work by visiting this website:

https://www.cursemaven.com/test/442962/3215435

Hope this helps!
P.S, I'm pretty sure it's up now, and if there's anything I can do to help fix your workspace let me know :)

**Comment by Jackiecrazy** [comment] 2021-02-25 08:54
I tried just now, and it still does not build. Looks like it's not actually searching in cursemaven. Does this look right in build.gradle?
```
buildscript {
    repositories {
        maven { url = 'https://files.minecraftforge.net/maven' }
        maven { url 'https://plugins.gradle.org/m2/' }
        maven { url = 'https://dist.creeper.host/Sponge/maven' }
        maven { url "https://www.cursemaven.com" }
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '3.+', changing: true
        classpath 'gradle.plugin.com.matthewprenger:CurseGradle:1.4.0'
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}
```

**Comment by ElenaiDev** [comment] 2021-02-25 08:59
Not quite! look at Elenai Dodge 2's build.gradle and you'll see that you need to create a new repository section from the buildscript :)

So scroll down to where you have 
```gradle
dependencies {
minecraft "..."
}
```
Then simply add a new repositories section above it, and put the dependency below minecraft.

Hope this helps!

**Comment by ElenaiDev** [comment] 2021-02-25 09:00
Closing this as the issue is not with Elenai Dodge, but feel free to continue posting here to receive support!

**Closed as completed by ElenaiDev** 2021-02-25 09:00 UTC

**Comment by Jackiecrazy** [comment] 2021-02-25 09:21
It works now, thank you. Does this make it an optional dependency?

**Comment by ElenaiDev** [comment] 2021-02-25 09:31
Yup, depending on how you implement it. Just make sure you don't access or import anything unless you know for sure it will be present.

Have a look at Elenai Dodge 2's ClientTickEventHandler for an example and have a great day!

Happy coding :)
